export enum CliErrorCode {
  TASK_NOT_FOUND = "TASK_NOT_FOUND",
  AMBIGUOUS_ID = "AMBIGUOUS_ID",
  PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND",
  TAG_NOT_FOUND = "TAG_NOT_FOUND",
  INVALID_DATE = "INVALID_DATE",
  INVALID_TIME = "INVALID_TIME",
  INVALID_MINUTES = "INVALID_MINUTES",
  INVALID_ARGUMENT = "INVALID_ARGUMENT",
  REFUSED = "REFUSED",
  SYNC_NOT_CONFIGURED = "SYNC_NOT_CONFIGURED",
  SYNC_FAILED = "SYNC_FAILED",
}
