export enum ServerSetupErrorCode {
  INVALID_ENVIRONMENT = "INVALID_ENVIRONMENT",
  OPENSSL_MISSING = "OPENSSL_MISSING",
  CERTIFICATE_FAILED = "CERTIFICATE_FAILED",
  VERIFICATION_FAILED = "VERIFICATION_FAILED",
  NOT_A_DAILY_SERVER = "NOT_A_DAILY_SERVER",
}
