export enum SyncServerErrorCode {
  UNREACHABLE = "UNREACHABLE",
  NOT_A_DAILY_SERVER = "NOT_A_DAILY_SERVER",
  PROTOCOL_VERSION_UNSUPPORTED = "PROTOCOL_VERSION_UNSUPPORTED",
  FINGERPRINT_MISMATCH = "FINGERPRINT_MISMATCH",
  INSECURE_TRANSPORT_REJECTED = "INSECURE_TRANSPORT_REJECTED",
  PROVIDER_CONFLICT = "PROVIDER_CONFLICT",
  NO_BINDING = "NO_BINDING",
}
