/** Stable wire codes for every way a Daily Sync Protocol request can be refused. */
export enum ProtocolErrorCode {
  MALFORMED_REQUEST = "MALFORMED_REQUEST",
  UNKNOWN_ROUTE = "UNKNOWN_ROUTE",
  METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED",
  PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE",
  UNAUTHORIZED = "UNAUTHORIZED",
  DEVICE_REVOKED = "DEVICE_REVOKED",
  ALREADY_CLAIMED = "ALREADY_CLAIMED",
  INVALID_CLAIM_CODE = "INVALID_CLAIM_CODE",
  CLAIM_CODE_LOCKED = "CLAIM_CODE_LOCKED",
  SERVER_NOT_CLAIMED = "SERVER_NOT_CLAIMED",
  ENROLLMENT_IN_PROGRESS = "ENROLLMENT_IN_PROGRESS",
  ENROLLMENT_NOT_FOUND = "ENROLLMENT_NOT_FOUND",
  ENROLLMENT_NOT_PENDING = "ENROLLMENT_NOT_PENDING",
  ENROLLMENT_CODE_MISMATCH = "ENROLLMENT_CODE_MISMATCH",
  INVALID_ENROLLMENT_TOKEN = "INVALID_ENROLLMENT_TOKEN",
  INTERNAL = "INTERNAL",
}
