name: Release Daily App

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build & Release on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: mac
          - os: windows-latest
            platform: win
          - os: ubuntu-latest
            platform: linux

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.5.0'

      - name: Install pnpm
        run: npm install -g pnpm@10.12.1

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: pnpm run build:${{ matrix.platform }}
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Generate release notes from CHANGELOG.md
        shell: bash
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          echo "Using version: $VERSION"
          node scripts/release-notes.js "$VERSION"

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body_path: release-notes.md
          draft: false
          prerelease: false
          files: |
            dist/*.dmg
            dist/*.exe
            dist/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
